version: '3.3'

services:
  api-prod:
    container_name: api-prod
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - savalt

  client-prod:
    container_name: client-prod
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api-prod
    networks:
      - savalt

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/my-perfect-job.crt:/etc/ssl/my-perfect-job.crt
      - ./nginx/my-perfect-job.key:/etc/ssl/my-perfect-job.key
    depends_on:
      - api-prod
      - client-prod
    networks:
      - savalt

networks:
  savalt: